export const cats = {
  luna: {
    id: "luna",
    name: "Luna",
    avatar: "🐱",
    species: "Gato",
    age: "3 anos",
    note: "Muy tranquila y carinosa",
  },
  oso: {
    id: "oso",
    name: "Oso",
    avatar: "🐈",
    species: "Gato",
    age: "2 anos",
    note: "Jugueton y muy activo",
  },
  nina: {
    id: "nina",
    name: "Nina",
    avatar: "🐾",
    species: "Gato",
    age: "5 anos",
    note: "Le gusta dormir y estar en calma",
  },
};

export const scenarios = {
  normal: {
    label: "Dia normal",
    data: {
      temp: 38.3,
      movement: 0.24,
      battery: 82,
      sleepHours: 13.2,
      meals: 3,
      ate: true,
      playMinutes: 45,
      inactiveHours: 1.5,
      continuousActivityMinutes: 4,
      bleConnected: true,
      bleDisconnectedSeconds: 0,
      deviceMode: "MONITOREO_NORMAL",
      bufferRecords: 0,
      gnssActive: false,
      updatedAt: "14:35",
    },
  },
  tempAlta: {
    label: "Temperatura alta",
    data: {
      temp: 40.1,
      movement: 0.18,
      battery: 78,
      sleepHours: 12,
      meals: 1,
      ate: true,
      playMinutes: 8,
      inactiveHours: 3,
      continuousActivityMinutes: 2,
      bleConnected: true,
      bleDisconnectedSeconds: 0,
      deviceMode: "EVENTO_ANOMALO",
      bufferRecords: 0,
      gnssActive: false,
      updatedAt: "15:10",
    },
  },
  pocoApetito: {
    label: "Poco apetito",
    data: {
      temp: 38.1,
      movement: 0.1,
      battery: 76,
      sleepHours: 15.5,
      meals: 0,
      ate: false,
      playMinutes: 6,
      inactiveHours: 5,
      continuousActivityMinutes: 1,
      bleConnected: true,
      bleDisconnectedSeconds: 0,
      deviceMode: "MONITOREO_NORMAL",
      bufferRecords: 0,
      gnssActive: false,
      updatedAt: "16:05",
    },
  },
  jugoMucho: {
    label: "Alta actividad",
    data: {
      temp: 38.6,
      movement: 0.95,
      battery: 70,
      sleepHours: 10.8,
      meals: 3,
      ate: true,
      playMinutes: 92,
      inactiveHours: 0.5,
      continuousActivityMinutes: 18,
      bleConnected: true,
      bleDisconnectedSeconds: 0,
      deviceMode: "ALTA_ACTIVIDAD",
      bufferRecords: 0,
      gnssActive: false,
      updatedAt: "17:25",
    },
  },
  decaido: {
    label: "Decaimiento",
    data: {
      temp: 37.4,
      movement: 0.05,
      battery: 74,
      sleepHours: 19,
      meals: 1,
      ate: true,
      playMinutes: 2,
      inactiveHours: 7,
      continuousActivityMinutes: 0,
      bleConnected: true,
      bleDisconnectedSeconds: 0,
      deviceMode: "EVENTO_ANOMALO",
      bufferRecords: 0,
      gnssActive: false,
      updatedAt: "18:10",
    },
  },
  zonaSegura: {
    label: "Zona segura",
    data: {
      temp: 38.4,
      movement: 0.36,
      battery: 48,
      sleepHours: 12.4,
      meals: 2,
      ate: true,
      playMinutes: 34,
      inactiveHours: 1,
      continuousActivityMinutes: 6,
      bleConnected: false,
      bleDisconnectedSeconds: 58,
      deviceMode: "EVENTO_CRITICO",
      bufferRecords: 12,
      gnssActive: true,
      location: {
        lat: 4.711,
        lng: -74.0721,
      },
      updatedAt: "19:15",
    },
  },
};

export const initialHistories = {
  luna: [
    {
      time: "09:00",
      temp: 38.2,
      movement: 0.22,
      sleepHours: 12.8,
      meals: 1,
      playMinutes: 18,
      mood: "Tranquila",
      state: "Normal",
      score: 95,
    },
    {
      time: "11:30",
      temp: 38.4,
      movement: 0.25,
      sleepHours: 13,
      meals: 2,
      playMinutes: 28,
      mood: "Relajada",
      state: "Normal",
      score: 96,
    },
    {
      time: "13:10",
      temp: 38.3,
      movement: 0.24,
      sleepHours: 13.1,
      meals: 2,
      playMinutes: 36,
      mood: "Contenta",
      state: "Normal",
      score: 97,
    },
  ],
  oso: [
    {
      time: "09:20",
      temp: 38.5,
      movement: 0.42,
      sleepHours: 11.5,
      meals: 1,
      playMinutes: 30,
      mood: "Activo",
      state: "Normal",
      score: 94,
    },
    {
      time: "12:40",
      temp: 38.6,
      movement: 0.55,
      sleepHours: 11.8,
      meals: 2,
      playMinutes: 55,
      mood: "Muy activo",
      state: "Normal",
      score: 96,
    },
  ],
  nina: [
    {
      time: "10:10",
      temp: 38.1,
      movement: 0.15,
      sleepHours: 15.5,
      meals: 1,
      playMinutes: 10,
      mood: "Calmada",
      state: "Normal",
      score: 95,
    },
    {
      time: "14:00",
      temp: 38,
      movement: 0.12,
      sleepHours: 16.2,
      meals: 2,
      playMinutes: 14,
      mood: "Relajada",
      state: "Normal",
      score: 96,
    },
  ],
};
